// Fahim
export const business_Data = [
    {
        id: 1,
        business_name: "Daraz",
        country: "Bangladesh",
        last_login: "2024-12-05 09:30",
        status: "Active",
    },
    {
        id: 2,
        business_name: "Adidas",
        country: "USA",
        last_login: "2024-12-05 09:30",
        status: "Active",
    },
    {
        id: 3,
        business_name: "Amazon",
        country: "UK",
        last_login: "2024-12-05 09:30",
        status: "Locked",
    },
    {
        id: 4,
        business_name: "Rolex",
        country: "UK",
        last_login: "2024-12-05 09:30",
        status: "Active",
    },
    {
        id: 5,
        business_name: "Chilox",
        country: "Bangladesh",
        last_login: "2024-12-05 09:30",
        status: "Active",
    },
    {
        id: 6,
        business_name: "Unilever",
        country: "Germany",
        last_login: "2024-12-05 09:30",
        status: "Locked",
    },
    {
        id: 7,
        business_name: "Nivea Men",
        country: "France",
        last_login: "2024-12-05 09:30",
        status: "Locked",
    },
    {
        id: 8,
        business_name: "Laurial Paris",
        country: "France",
        last_login: "2024-12-05 09:30",
        status: "Active",
    },
    {
        id: 9,
        business_name: "Dell",
        country: "USA",
        last_login: "2024-12-05 09:30",
        status: "Active",
    },
    {
        id: 10,
        business_name: "HP",
        country: "USA",
        last_login: "2024-12-05 09:30",
        status: "Locked",
    },
    {
        id: 11,
        business_name: "ASUS",
        country: "Taiwan",
        last_login: "2024-12-05 09:30",
        status: "Locked",
    },
    {
        id: 12,
        business_name: "Oleves",
        country: "China",
        last_login: "2024-12-05 09:30",
        status: "Active",
    },
    {
        id: 13,
        business_name: "Transcend",
        country: "Taiwan",
        last_login: "2024-12-05 09:30",
        status: "Locked",
    },
    {
        id: 14,
        business_name: "Fantech",
        country: "Phillipines",
        last_login: "2024-12-05 09:30",
        status: "Active",
    },
    {
        id: 15,
        business_name: "Logitech",
        country: "Switzerland",
        last_login: "2024-12-05 09:30",
        status: "Active",
    },
    {
        id: 16,
        business_name: "BenQ",
        country: "Taiwan",
        last_login: "2024-12-05 09:30",
        status: "Active",
    },
];




export interface BusinessCardData {
    id: number;
    business_name: string;
    country: string;
    email: string;
    created_date: string;
    last_login: string;
    status: string;
    banner_src: string;
    flag_src: string; // This should be country code like "BD", "AE", etc.
    description: string;
    services: string[];
}

export const allBusinessData = [
    {
        id: 1,
        business_name: "Daraz",
        country: "Bangladesh",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/1.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 2,
        business_name: "Adidas",
        country: "USA",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/2.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 3,
        business_name: "Amazon",
        country: "UK",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/3.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 4,
        business_name: "Rolex",
        country: "UK",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/4.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 5,
        business_name: "Chilox",
        country: "Bangladesh",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/5.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 6,
        business_name: "Unilever",
        country: "Germany",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 7,
        business_name: "Nivea Men",
        country: "France",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 8,
        business_name: "Laurial Paris",
        country: "France",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 9,
        business_name: "Dell",
        country: "USA",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 10,
        business_name: "HP",
        country: "USA",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 11,
        business_name: "ASUS",
        country: "Taiwan",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 12,
        business_name: "Oleves",
        country: "China",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 13,
        business_name: "Transcend",
        country: "Taiwan",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 14,
        business_name: "Fantech",
        country: "Phillipines",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 15,
        business_name: "Logitech",
        country: "Switzerland",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 16,
        business_name: "BenQ",
        country: "Taiwan",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 17,
        business_name: "Daraz",
        country: "Bangladesh",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 18,
        business_name: "Adidas",
        country: "USA",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 19,
        business_name: "Amazon",
        country: "UK",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 20,
        business_name: "Rolex",
        country: "UK",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 21,
        business_name: "Chilox",
        country: "Bangladesh",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 22,
        business_name: "Unilever",
        country: "Germany",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 23,
        business_name: "Nivea Men",
        country: "France",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 24,
        business_name: "Laurial Paris",
        country: "France",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 25,
        business_name: "Dell",
        country: "USA",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 26,
        business_name: "HP",
        country: "USA",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 27,
        business_name: "ASUS",
        country: "Taiwan",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 28,
        business_name: "Oleves",
        country: "China",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 29,
        business_name: "Transcend",
        country: "Taiwan",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Locked",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 30,
        business_name: "Fantech",
        country: "Phillipines",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 31,
        business_name: "Logitech",
        country: "Switzerland",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
    {
        id: 32,
        business_name: "BenQ",
        country: "Taiwan",
        email: "saikhseraj2017@gmail.com",
        created_date: "2024-01-05",
        last_login: "2024-12-05 09:30",
        status: "Active",
        banner_src: "/all-business-card-banners/6.jpg",
        flag_src: "🇦🇪",
        description: `Full-service construction company delivering high-quality projects across the 
        Middle East`,
        services: ["Commercial Construction", "Project Management", "Course Development"],
    },
];




