// Fahim
import type { Metadata } from "next";
import "@/app/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
// import { cookies } from "next/headers";
import AppSidebar from "../components/common/AppSidebar";
import Navbar from "../components/common/NavBar";

export const metadata: Metadata = {
    title: "Super Admin",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // const cookieStore = await cookies();
    // const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

    return (
        <html lang="en">
            <body className={`antialiased`}>
                <SidebarProvider>
                    <AppSidebar />
                    <main className="w-full">
                        <Navbar />
                        <div className="px-4">
                            {children}
                        </div>
                    </main>
                </SidebarProvider>
            </body>
        </html>
    );
}

