// Fahim
"use client"
import type { Metadata } from "next";
import "@/app/globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
// import { cookies } from "next/headers";
import AppSidebar from "../../components/common/AppSidebar";
import { ViewProvider } from "../../ListGridContext";
import { Poppins } from "next/font/google";
import NavBarWithTrigger from "../../components/common/NavBarWithTrigger";
import { FilterProvider } from "../../FilterContext";

const poppinsFont = Poppins({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800", "900"],
    variable: "--font-poppins"
});

// export const metadata: Metadata = {
//     title: "Super Admin",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    // const cookieStore = await cookies();
    // const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

    return (
        <section>
            <div className={`${poppinsFont.variable} antialiased`}>
                <FilterProvider>
                    <ViewProvider>
                        <SidebarProvider>
                            <AppSidebar />
                            <main className="w-full">
                                <NavBarWithTrigger />
                                {children}
                            </main>
                        </SidebarProvider>
                    </ViewProvider>
                </FilterProvider>
            </div>
        </section>
    );
}

